# Generated by Django 4.1 on 2024-02-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="1995-04-12"),
            preserve_default=False,
        ),
    ]
