# Generated by Django 4.2.9 on 2024-02-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0002_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Place",
        ),
    ]
