# Generated by Django 4.2.9 on 2024-02-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0003_delete_place"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="Place",
        ),
    ]
