# Generated by Django 4.1 on 2024-02-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0004_rename_group_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("img", models.ImageField(upload_to="pics")),
                ("desc", models.TextField()),
            ],
        ),
    ]
